name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  APP_ID:
    description: 'App ID From Splunkbase'
    required: true
    default: '5596'
  SPLUNK_USERNAME:
    description: 'Splunkbase Username'
    required: true
  SPLUNK_PASSWORD:
    description: 'Splunkbase Password'
    required: true
  APP_FILE:
    description: 'The name of the file, for example "my_package.tar.gz".'
    required: true
  SPLUNK_VERSION:
    description: 'The Splunk version(s) that the release is compatible with. For example, "8.0,8.1,8.2".'
    required: true
  VISIBILITY:
    description: 'true = The release is to be visible upon package validation success. false = if the release is to be hidden.'
    required: false
    default: 'false'
  CIM_VERSIONS:
    description: 'The CIM version(s) that the release is compatible with. For example, "4.9,4.7".'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
