name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  AppID:
    description: 'App ID From Splunkbase'
    required: true
    default: '5596'
  splunkUser:
    description: 'Splunkbase Username'
    required: true
  splunkPassword:
    description: 'Splunkbase Password'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'